apiVersion: skaffold/v4beta9
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  local: {}
manifests:
  rawYaml:
    - manifests:
  rawYaml:
    - /workspace/source/deploy/manifest.yaml

deploy:
  kubectl: {}
  logs:
    prefix: container
