apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: ey-task-cicd
  labels:
    app: cicd
description: cicd delivery pipeline
serialPipeline:
  stages:
  - targetId: dev
    profiles: []
    
